module.exports = {
  testEnvironment: 'node',
  roots: ['<rootDir>/tests'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  preset: 'ts-jest',
  testTimeout: 10000,
  verbose: true,
  collectCoverage: false,
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  coverageProvider: 'v8',
  maxWorkers: '50%',
  workerIdleMemoryLimit: '512MB',
  maxConcurrency: 5,
  injectGlobals: true,
  cache: true,
  cacheDirectory: '<rootDir>/.jest-cache',
  testPathIgnorePatterns: ['/node_modules/', '/dist/', '/coverage/', '/logs/'],
  moduleNameMapper: {
    '^@config/(.*)$': '<rootDir>/config/$1',
    '^@controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@cron/(.*)$': '<rootDir>/cron/$1',
    '^@exceptions/(.*)$': '<rootDir>/src/exceptions/$1',
    '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@models/(.*)$': '<rootDir>/src/models/$1',
    '^@requests/(.*)$': '<rootDir>/src/requests/$1',
    '^@resources/(.*)$': '<rootDir>/src/resources/$1',
    '^@routes/(.*)$': '<rootDir>/routes/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@container/(.*)$': '<rootDir>/src/container/$1',
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.test.json',
        diagnostics: {
          ignoreCodes: [1343],
        },
      },
    ],
  },
  reporters: ['default'],
  testEnvironmentOptions: {
    url: 'http://localhost',
  },
  forceExit: true,
  detectOpenHandles: true,
  randomize: true,
};
